### PR TITLE
Provide a built-in event  bus system for all users

### PR DESCRIPTION
**Pull request by SAGESSE-CN**
Example:

Hidden the `Hunger` and `Saturation` values of `Apple` in tooltip:
```java
TooltipOverlayEvent.Pre.EVENT.register(event -> {
	if (event.itemStack.getItem().toString().contains("apple")) {
		event.isCanceled = true;
	}
});
```

Hidden the `Hunger` values of `Apple` in HUD:
```java
HUDOverlayEvent.Hunger.EVENT.register(event -> {
	if (event.itemStack.getItem().toString().contains("apple")) {
		event.isCanceled = true;
	}
});
```

### CODE REVIEW

**Comment by SAGESSE-CN** [comment]
Fixes: #94

**Comment by squeek502** [comment]
Thanks for doing this! Commenting here but this applies to #100 too.

- I understand that you wanted to have the same system for both Fabric and Forge, but I'm not sure it's worth doing that for this. I think it'd be better to do things ['the Fabric way'](https://fabricmc.net/wiki/tutorial:events) for Fabric and 'the Forge way' for Forge.
- One thing to be aware of is which classes need to be available to mods when they are using these events--we want to minimize that as much as possible, and make it all self-contained. If a mod needs to import a class like `squeek.appleskin.AppleSkin` that is going to make it difficult for them to add optional support for AppleSkin, whereas if they only need to import a self-contained API class, then they can easily make it so their mod still works fine if AppleSkin is not installed.
  - Typically, these types of classes are put into a separate API package path which only imports other things inside the API package path
- ~~I think it might be okay to start with very basic events, i.e. just being able to cancel the rendering of the HUD stuff. I can't think of many use cases for the rest.~~ EDIT: Changed my mind, I think the events you have are good.

**Comment by SAGESSE-CN** [comment]
I did consider using the Fabric API to implement an EventBus
1. somebody need changes rendering parameters, such as modifying the position of the render or cancel event
2. multiple events var required instead of a simple register point

**Comment by squeek502** [comment]
I think it's possible to allow changing the parameters by doing something like:

```java
    public interface TooltipOverlayEventPreCallback {
     
        Event<TooltipOverlayEventPreCallback> EVENT = EventFactory.createArrayBacked(TooltipOverlayEventPreCallback.class,
            (listeners) -> (event) -> {
                for (TooltipOverlayEventPreCallback listener : listeners) {
                    event = listener.interact(event);
     
                    if(event.isCanceled) {
                        return event;
                    }
                }
     
            return event;
        });
     
        TooltipOverlayEvent.Pre interact(TooltipOverlayEvent.Pre event);
    }
```

so then firing the event would look something like this:

```java
TooltipOverlayEvent.Pre prerenderEvent = new TooltipOverlayEvent.Pre(hoveredStack, defaultFoodValues, modifiedFoodValues);
prerenderEvent = TooltipOverlayEventPreCallback.EVENT.invoker().interact(prerenderEvent);
if (prerenderEvent.isCanceled) {
	return;
}
```

**Pull request merged**
